package providers

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Adapter defines the strategy that each AI provider adapter must implement.
type Adapter interface {
	// Name returns the unique identifier for the adapter (e.g. "devin", "goose").
	Name() string

	// Compile reads canonical configuration files from cockpitHomeDir
	// and returns a map of relative target file paths to their generated file contents.
	Compile(cockpitHomeDir string, provider *Provider) (map[string]string, error)
}

// StripFrontmatter parses YAML-style frontmatter from a markdown file's content.
// It returns a map of parsed key-value pairs and the body content without frontmatter.
// Frontmatter must be delimited by "---" on its own line.
func StripFrontmatter(content string) (map[string]string, string) {
	lines := strings.Split(content, "\n")
	if len(lines) == 0 || strings.TrimSpace(lines[0]) != "---" {
		return nil, content
	}

	endIdx := -1
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "---" {
			endIdx = i
			break
		}
	}

	if endIdx == -1 {
		return nil, content
	}

	fmLines := lines[1:endIdx]
	var bodyBuilder strings.Builder
	for i := endIdx + 1; i < len(lines); i++ {
		bodyBuilder.WriteString(lines[i])
		if i < len(lines)-1 {
			bodyBuilder.WriteString("\n")
		}
	}
	body := strings.TrimSpace(bodyBuilder.String())

	frontmatter := make(map[string]string)
	for _, line := range fmLines {
		if strings.Contains(line, ":") {
			parts := strings.SplitN(line, ":", 2)
			key := strings.TrimSpace(parts[0])
			value := strings.TrimSpace(parts[1])
			// Strip optional quotes
			value = strings.Trim(value, "\"'")
			frontmatter[key] = value
		}
	}

	return frontmatter, body
}

// AddGeneratedHeader prepends a "do not edit" warning header to generated contents.
// For files with YAML frontmatter (starting with ---), the header is injected
// after the closing --- so parsers can still read the frontmatter correctly.
func AddGeneratedHeader(content string, adapterName string) string {
	var header string
	if filepath.Ext(adapterName) == ".yaml" || filepath.Ext(adapterName) == ".yml" || strings.HasPrefix(adapterName, ".") {
		// Use bash/yaml-style comments
		header = fmt.Sprintf("# GENERATED by AICockpit %s adapter. Do not edit directly.\n# Edit rules/skills inside ~/.cockpit/ then run: cockpit deploy\n\n", adapterName)
		return header + content
	}

	htmlHeader := fmt.Sprintf("<!-- GENERATED by AICockpit %s adapter. Do not edit directly. -->\n<!-- GENERATED: Edit rules/skills inside ~/.cockpit/ then run: cockpit deploy -->\n\n", adapterName)

	// If content has YAML frontmatter (starts with ---), inject header AFTER it
	// so Antigravity/providers can still parse name/description from frontmatter.
	trimmed := strings.TrimLeft(content, "\r\n")
	if strings.HasPrefix(trimmed, "---") {
		// Find the closing ---
		rest := trimmed[3:] // skip opening ---
		closingIdx := strings.Index(rest, "\n---")
		if closingIdx >= 0 {
			// closingIdx points to \n--- ; skip past the closing --- line
			afterClose := rest[closingIdx+4:] // skip \n---
			// skip the newline after closing ---
			if len(afterClose) > 0 && afterClose[0] == '\n' {
				afterClose = afterClose[1:]
			}
			frontmatter := "---" + rest[:closingIdx+4] // opening + body + \n---
			return frontmatter + "\n" + htmlHeader + afterClose
		}
	}

	return htmlHeader + content
}

// ReadCanonicalFile helper to read a canonical file from the cockpit home directory.
func ReadCanonicalFile(cockpitHomeDir string, pathParts ...string) (string, error) {
	fullPath := filepath.Join(append([]string{cockpitHomeDir}, pathParts...)...)
	data, err := os.ReadFile(fullPath)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// ReadCanonicalDir helper to list all files matching a pattern in a canonical directory.
func ReadCanonicalDir(cockpitHomeDir string, pathParts ...string) ([]string, error) {
	dirPath := filepath.Join(append([]string{cockpitHomeDir}, pathParts...)...)
	entries, err := os.ReadDir(dirPath)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	var files []string
	for _, entry := range entries {
		if !entry.IsDir() {
			files = append(files, entry.Name())
		}
	}
	return files, nil
}
