package providers

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

var _ Compiler = (*CodexCompiler)(nil)

func codexProvider(features map[string]*FeatureConfig) *Provider {
	return &Provider{Features: features}
}

func TestCodexCompiler_Name(t *testing.T) {
	compiler := NewCodexCompiler()

	if got := compiler.Name(); got != codexProviderName {
		t.Fatalf("Name() = %q, want %q", got, codexProviderName)
	}
}

func TestCodexCompiler_CompileEntrypoint(t *testing.T) {
	compiler := NewCodexCompiler()
	provider := codexProvider(map[string]*FeatureConfig{
		"rules": {Enabled: true, Path: "AGENTS.md"},
	})

	tests := []struct {
		name       string
		entrypoint *CanonicalEntrypoint
		wantErr    string
		want       string
	}{
		{
			name: "context and golden rules",
			entrypoint: &CanonicalEntrypoint{
				ProjectContext: "Project context",
				GoldenRules:    []string{" first rule ", "", "second rule"},
			},
			want: "Project context\n\n## AICockpit Gold Rules\n\nfirst rule\n\nsecond rule",
		},
		{
			name:       "empty entrypoint still creates target",
			entrypoint: &CanonicalEntrypoint{},
			want:       "",
		},
		{
			name:       "nil entrypoint",
			entrypoint: nil,
			wantErr:    "entrypoint cannot be nil",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			files, err := compiler.CompileEntrypoint(tt.entrypoint, provider)
			if tt.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("CompileEntrypoint() error = %v, want substring %q", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("CompileEntrypoint() error = %v", err)
			}
			got, ok := files["AGENTS.md"]
			if !ok {
				t.Fatalf("CompileEntrypoint() did not create AGENTS.md: %#v", files)
			}
			if !strings.Contains(got, "<!-- GENERATED by AICockpit codex adapter") {
				t.Errorf("generated header missing from %q", got)
			}
			if !strings.Contains(got, tt.want) {
				t.Errorf("compiled content = %q, want it to contain %q", got, tt.want)
			}
		})
	}
}

func TestCodexCompiler_CompileRules(t *testing.T) {
	compiler := NewCodexCompiler()
	provider := codexProvider(map[string]*FeatureConfig{
		"rules": {Enabled: true, Path: "AGENTS.md"},
	})

	files, err := compiler.CompileRules([]CanonicalRule{
		{Name: "z-rule", Content: "Z rule"},
		{Name: "empty", Content: "  "},
		{Name: "a-rule", Content: "A rule"},
	}, provider)
	if err != nil {
		t.Fatalf("CompileRules() error = %v", err)
	}
	if got, want := files["AGENTS.md"], "A rule\n\n---\n\nZ rule"; got != want {
		t.Errorf("compiled rules = %q, want %q", got, want)
	}

	tests := []struct {
		name     string
		rules    []CanonicalRule
		provider *Provider
		wantLen  int
	}{
		{name: "no rules", rules: nil, provider: provider, wantLen: 0},
		{
			name:     "only blank rules",
			rules:    []CanonicalRule{{Name: "blank", Content: "\n  "}},
			provider: provider,
			wantLen:  0,
		},
		{
			name:  "disabled feature",
			rules: []CanonicalRule{{Name: "rule", Content: "content"}},
			provider: codexProvider(map[string]*FeatureConfig{
				"rules": {Enabled: false, Path: "AGENTS.md"},
			}),
			wantLen: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			files, err := compiler.CompileRules(tt.rules, tt.provider)
			if err != nil {
				t.Fatalf("CompileRules() error = %v", err)
			}
			if len(files) != tt.wantLen {
				t.Errorf("CompileRules() returned %d files, want %d", len(files), tt.wantLen)
			}
		})
	}
}

func TestCodexCompiler_CompileSkills(t *testing.T) {
	compiler := NewCodexCompiler()
	provider := codexProvider(map[string]*FeatureConfig{
		"skills": {Enabled: true, Path: ".agents/skills"},
	})

	files, err := compiler.CompileSkills([]CanonicalSkill{
		{
			Name:        "release",
			Description: "Release helper",
			Content:     "Use the release checklist.",
			ScriptFiles: map[string]string{"scripts/z.sh": "z", "scripts/a.sh": "a"},
		},
		{Name: "review", Description: "Review helper", Content: "Review the diff."},
	}, provider)
	if err != nil {
		t.Fatalf("CompileSkills() error = %v", err)
	}

	releasePath := filepath.Join(".agents/skills", "release", "SKILL.md")
	release, ok := files[releasePath]
	if !ok {
		t.Fatalf("missing %s in %#v", releasePath, files)
	}
	if !strings.HasPrefix(release, "---\n") {
		t.Fatalf("skill frontmatter was not kept first: %q", release)
	}
	if !strings.Contains(release, "name: \"release\"") || !strings.Contains(release, "Use the release checklist.") {
		t.Errorf("unexpected compiled skill: %q", release)
	}
	if !strings.Contains(release, "<!-- GENERATED by AICockpit codex adapter") {
		t.Errorf("generated header missing from skill: %q", release)
	}
	if got := files[filepath.Join(".agents/skills", "release", "scripts", "a.sh")]; got != "a" {
		t.Errorf("a.sh = %q, want %q", got, "a")
	}
	if got := files[filepath.Join(".agents/skills", "release", "scripts", "z.sh")]; got != "z" {
		t.Errorf("z.sh = %q, want %q", got, "z")
	}
	if _, ok := files[filepath.Join(".agents/skills", "review", "SKILL.md")]; !ok {
		t.Error("second skill was not compiled")
	}

	tests := []struct {
		name  string
		skill CanonicalSkill
	}{
		{name: "invalid skill name", skill: CanonicalSkill{Name: "../release"}},
		{
			name: "script escapes skill directory",
			skill: CanonicalSkill{
				Name:        "release",
				ScriptFiles: map[string]string{"../outside.sh": "unsafe"},
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := compiler.CompileSkills([]CanonicalSkill{tt.skill}, provider); err == nil {
				t.Error("CompileSkills() expected validation error")
			}
		})
	}
}

func TestCodexCompiler_CompileWorkflows(t *testing.T) {
	compiler := NewCodexCompiler()
	provider := codexProvider(map[string]*FeatureConfig{
		"workflows": {Enabled: true, Path: ".agents/skills"},
	})

	files, err := compiler.CompileWorkflows([]CanonicalWorkflow{
		{Name: "deploy", Description: "Deploy the project", Steps: []string{"build", "ship"}},
		{Name: "check", Steps: []string{"test"}},
	}, provider)
	if err != nil {
		t.Fatalf("CompileWorkflows() error = %v", err)
	}

	path := filepath.Join(".agents/skills", "deploy", "SKILL.md")
	content, ok := files[path]
	if !ok {
		t.Fatalf("missing %s in %#v", path, files)
	}
	for _, expected := range []string{"name: \"deploy\"", "# Workflow: deploy", "1. build", "2. ship", "Deploy the project"} {
		if !strings.Contains(content, expected) {
			t.Errorf("workflow content %q does not contain %q", content, expected)
		}
	}
	if !strings.Contains(content, "<!-- GENERATED by AICockpit codex adapter") {
		t.Errorf("generated header missing from workflow: %q", content)
	}

	tests := []struct {
		name     string
		workflow CanonicalWorkflow
	}{
		{name: "invalid workflow name", workflow: CanonicalWorkflow{Name: "a/b"}},
		{name: "empty workflows", workflow: CanonicalWorkflow{}},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := compiler.CompileWorkflows([]CanonicalWorkflow{tt.workflow}, provider); err == nil {
				t.Error("CompileWorkflows() expected validation error")
			}
		})
	}

	files, err = compiler.CompileWorkflows(nil, provider)
	if err != nil {
		t.Fatalf("CompileWorkflows(nil) error = %v", err)
	}
	if len(files) != 0 {
		t.Errorf("CompileWorkflows(nil) returned %d files, want 0", len(files))
	}
}

func TestCodexCompiler_CompilePermissions(t *testing.T) {
	compiler := NewCodexCompiler()
	provider := codexProvider(map[string]*FeatureConfig{
		"permissions": {Enabled: true, Path: ".codex/rules"},
	})

	files, err := compiler.CompilePermissions(&CanonicalPermissions{
		AllowedCommands: []string{"git status", "git status", "make"},
		DeniedCommands:  []string{"rm -rf"},
		AllowedDirs:     []string{"src"},
		Allow:           []string{"Exec(go test ./...)", "Read(src/**)"},
		Deny:            []string{"Exec(rm -rf build)"},
		Ask:             []string{"Exec(git push)", "network"},
	}, provider)
	if err != nil {
		t.Fatalf("CompilePermissions() error = %v", err)
	}

	path := filepath.Join(".codex/rules", "aicockpit.rules")
	content, ok := files[path]
	if !ok {
		t.Fatalf("missing %s in %#v", path, files)
	}
	for _, expected := range []string{
		"# GENERATED by AICockpit .rules adapter",
		`pattern = ["git", "status"]`,
		`decision = "allow"`,
		`pattern = ["rm", "-rf"]`,
		`decision = "forbidden"`,
		`pattern = ["go", "test", "./..."]`,
		`pattern = ["git", "push"]`,
		`decision = "prompt"`,
		"allowed_dirs requires Codex sandbox configuration",
		`allow entry "Read(src/**)" is not a Codex command`,
		`ask entry "network" is not a Codex command`,
	} {
		if !strings.Contains(content, expected) {
			t.Errorf("permission content does not contain %q: %s", expected, content)
		}
	}
	if got := strings.Count(content, `pattern = ["git", "status"]`); got != 1 {
		t.Errorf("duplicate allow rule count = %d, want 1", got)
	}

	tests := []struct {
		name     string
		perms    *CanonicalPermissions
		provider *Provider
		wantLen  int
	}{
		{name: "nil permissions", perms: nil, provider: provider, wantLen: 0},
		{name: "empty permissions", perms: &CanonicalPermissions{}, provider: provider, wantLen: 0},
		{
			name:     "warnings without rules",
			perms:    &CanonicalPermissions{AllowedDirs: []string{"src"}},
			provider: provider,
			wantLen:  1,
		},
		{
			name: "invalid quoted command",
			perms: &CanonicalPermissions{
				AllowedCommands: []string{`echo "unfinished`},
			},
			provider: provider,
			wantLen:  -1,
		},
		{
			name: "file path already has rules extension",
			perms: &CanonicalPermissions{
				AllowedCommands: []string{"go"},
			},
			provider: codexProvider(map[string]*FeatureConfig{
				"permissions": {Enabled: true, Path: ".codex/custom.rules"},
			}),
			wantLen: 1,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			files, err := compiler.CompilePermissions(tt.perms, tt.provider)
			if tt.wantLen < 0 {
				if err == nil || !strings.Contains(err.Error(), "invalid Codex permission command") {
					t.Fatalf("CompilePermissions() error = %v, want invalid command error", err)
				}
				return
			}
			if err != nil {
				t.Fatalf("CompilePermissions() error = %v", err)
			}
			if len(files) != tt.wantLen {
				t.Errorf("CompilePermissions() returned %d files, want %d", len(files), tt.wantLen)
			}
			if tt.name == "file path already has rules extension" {
				if _, ok := files[".codex/custom.rules"]; !ok {
					t.Errorf("expected direct .rules path in %#v", files)
				}
			}
		})
	}
}

func TestCodexCompiler_CompileAgents(t *testing.T) {
	compiler := NewCodexCompiler()
	provider := codexProvider(map[string]*FeatureConfig{
		"agents": {Enabled: true, Path: ".codex/agents"},
	})

	files, err := compiler.CompileAgents([]CanonicalAgent{
		{
			Name:         "reviewer",
			Description:  "Reviews changes",
			Model:        "gpt-5-codex",
			AllowedTools: []string{"read"},
			Permissions:  map[string]interface{}{"allow": []string{"read"}},
			Content:      "Review the change carefully.",
			MaxNesting:   2,
		},
		{Name: "simple", Description: "Simple agent", Content: "Do the task."},
	}, provider)
	if err != nil {
		t.Fatalf("CompileAgents() error = %v", err)
	}

	path := filepath.Join(".codex/agents", "reviewer.toml")
	content, ok := files[path]
	if !ok {
		t.Fatalf("missing %s in %#v", path, files)
	}
	for _, expected := range []string{
		"# GENERATED by AICockpit .toml adapter",
		"# WARNING: allowed_tools is provider-specific",
		"# WARNING: agent permissions are provider-specific",
		"# WARNING: max_nesting is not supported",
		`name = "reviewer"`,
		`description = "Reviews changes"`,
		`model = "gpt-5-codex"`,
		`developer_instructions = "Review the change carefully."`,
	} {
		if !strings.Contains(content, expected) {
			t.Errorf("agent content does not contain %q: %s", expected, content)
		}
	}

	simple := files[filepath.Join(".codex/agents", "simple.toml")]
	if strings.Contains(simple, "model =") || strings.Contains(simple, "WARNING") {
		t.Errorf("simple agent unexpectedly contains optional fields or warnings: %s", simple)
	}

	if _, err := compiler.CompileAgents([]CanonicalAgent{{Name: "bad/name"}}, provider); err == nil {
		t.Error("CompileAgents() expected invalid name error")
	}
	if files, err := compiler.CompileAgents(nil, provider); err != nil || len(files) != 0 {
		t.Errorf("CompileAgents(nil) = %#v, %v; want empty result", files, err)
	}
}

func TestCodexCompiler_FeatureStates(t *testing.T) {
	compiler := NewCodexCompiler()
	rules := []CanonicalRule{{Name: "rule", Content: "content"}}

	tests := []struct {
		name      string
		provider  *Provider
		wantErr   string
		wantFiles int
	}{
		{name: "nil provider", provider: nil, wantErr: "provider configuration cannot be nil"},
		{name: "missing feature", provider: codexProvider(nil), wantFiles: 0},
		{
			name: "nil feature",
			provider: codexProvider(map[string]*FeatureConfig{
				"rules": nil,
			}),
			wantFiles: 0,
		},
		{
			name: "disabled feature",
			provider: codexProvider(map[string]*FeatureConfig{
				"rules": {Enabled: false, Path: "AGENTS.md"},
			}),
			wantFiles: 0,
		},
		{
			name: "enabled feature without path",
			provider: codexProvider(map[string]*FeatureConfig{
				"rules": {Enabled: true},
			}),
			wantErr: "enabled but has no path",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			files, err := compiler.CompileRules(rules, tt.provider)
			if tt.wantErr != "" {
				if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
					t.Fatalf("CompileRules() error = %v, want substring %q", err, tt.wantErr)
				}
				return
			}
			if err != nil {
				t.Fatalf("CompileRules() error = %v", err)
			}
			if len(files) != tt.wantFiles {
				t.Errorf("CompileRules() returned %d files, want %d", len(files), tt.wantFiles)
			}
		})
	}
}

func TestCodexValidationHelpers(t *testing.T) {
	artifactTests := []struct {
		name    string
		value   string
		wantErr bool
	}{
		{name: "normal", value: "reviewer"},
		{name: "empty", value: "", wantErr: true},
		{name: "whitespace", value: " ", wantErr: true},
		{name: "leading whitespace", value: " reviewer", wantErr: true},
		{name: "trailing whitespace", value: "reviewer ", wantErr: true},
		{name: "slash", value: "review/reviewer", wantErr: true},
		{name: "backslash", value: `review\review`, wantErr: true},
		{name: "dot", value: ".", wantErr: true},
		{name: "dot dot", value: "..", wantErr: true},
	}
	for _, tt := range artifactTests {
		t.Run("artifact/"+tt.name, func(t *testing.T) {
			err := validateCodexArtifactName(tt.value, "skill")
			if (err != nil) != tt.wantErr {
				t.Errorf("validateCodexArtifactName(%q) error = %v, wantErr %t", tt.value, err, tt.wantErr)
			}
		})
	}

	pathTests := []struct {
		name    string
		value   string
		wantErr bool
	}{
		{name: "nested", value: "scripts/deploy.sh"},
		{name: "cleanable nested", value: "scripts/../deploy.sh"},
		{name: "empty", value: "", wantErr: true},
		{name: "absolute", value: "/tmp/deploy.sh", wantErr: true},
		{name: "backslash", value: `scripts\deploy.sh`, wantErr: true},
		{name: "current directory", value: ".", wantErr: true},
		{name: "parent directory", value: "..", wantErr: true},
		{name: "parent escape", value: "../deploy.sh", wantErr: true},
		{name: "nested escape", value: "scripts/../../deploy.sh", wantErr: true},
	}
	for _, tt := range pathTests {
		t.Run("path/"+tt.name, func(t *testing.T) {
			err := validateCodexRelativePath(tt.value, "script")
			if (err != nil) != tt.wantErr {
				t.Errorf("validateCodexRelativePath(%q) error = %v, wantErr %t", tt.value, err, tt.wantErr)
			}
		})
	}
}

func TestCodexPermissionHelpers(t *testing.T) {
	tests := []struct {
		name   string
		value  string
		want   string
		wantOK bool
	}{
		{name: "exec expression", value: "Exec(git status)", want: "git status", wantOK: true},
		{name: "trimmed expression", value: " Exec( go test ) ", want: "go test", wantOK: true},
		{name: "empty expression", value: "Exec()", wantOK: false},
		{name: "different expression", value: "Read(src/**)", wantOK: false},
		{name: "missing close", value: "Exec(git", wantOK: false},
	}
	for _, tt := range tests {
		t.Run("expression/"+tt.name, func(t *testing.T) {
			got, ok := codexExecExpression(tt.value)
			if got != tt.want || ok != tt.wantOK {
				t.Errorf("codexExecExpression(%q) = %q, %t; want %q, %t", tt.value, got, ok, tt.want, tt.wantOK)
			}
		})
	}

	splitTests := []struct {
		name    string
		value   string
		want    []string
		wantErr bool
	}{
		{name: "plain", value: "git status --short", want: []string{"git", "status", "--short"}},
		{name: "quoted", value: `python -c "print('x y')"`, want: []string{"python", "-c", "print('x y')"}},
		{name: "escaped space", value: `echo a\ b`, want: []string{"echo", "a b"}},
		{name: "empty", value: "", wantErr: true},
		{name: "unterminated escape", value: `echo a\`, wantErr: true},
		{name: "unterminated quote", value: `echo "a`, wantErr: true},
	}
	for _, tt := range splitTests {
		t.Run("split/"+tt.name, func(t *testing.T) {
			got, err := splitCodexCommandPrefix(tt.value)
			if tt.wantErr {
				if err == nil {
					t.Error("splitCodexCommandPrefix() expected error")
				}
				return
			}
			if err != nil {
				t.Fatalf("splitCodexCommandPrefix() error = %v", err)
			}
			if !reflect.DeepEqual(got, tt.want) {
				t.Errorf("splitCodexCommandPrefix() = %#v, want %#v", got, tt.want)
			}
		})
	}

	if got := codexPermissionFilePath(".codex/rules"); got != filepath.Join(".codex/rules", "aicockpit.rules") {
		t.Errorf("codexPermissionFilePath(directory) = %q", got)
	}
	if got := codexPermissionFilePath(".codex/custom.rules"); got != ".codex/custom.rules" {
		t.Errorf("codexPermissionFilePath(file) = %q", got)
	}
}

func TestNewProviderManagerRegistersCodexCompiler(t *testing.T) {
	manager := NewProviderManager(&ProvidersConfig{})

	compiler, ok := manager.compilers[codexProviderName]
	if !ok {
		t.Fatal("Codex compiler was not registered")
	}
	if compiler.Name() != codexProviderName {
		t.Errorf("registered compiler name = %q, want %q", compiler.Name(), codexProviderName)
	}
}

func TestProviderManagerDeployCodex(t *testing.T) {
	cockpitDir := t.TempDir()
	projectDir := t.TempDir()

	writeCodexTestFile(t, filepath.Join(cockpitDir, "COCKPIT.md"), "Canonical project context")
	writeCodexTestFile(t, filepath.Join(cockpitDir, "rules", "quality.md"), "Keep changes tested.")
	writeCodexTestFile(t, filepath.Join(cockpitDir, "skills", "release", "SKILL.md"), "---\nname: release\ndescription: Release helper\n---\nRun the release checklist.\n")
	writeCodexTestFile(t, filepath.Join(cockpitDir, "workflows", "deploy.yaml"), "name: deploy\ndescription: Deploy safely\nsteps:\n  - test\n  - ship\n")
	writeCodexTestFile(t, filepath.Join(cockpitDir, "permissions.yaml"), "allowed_commands:\n  - git status\ndenied_commands:\n  - rm\n")
	writeCodexTestFile(t, filepath.Join(cockpitDir, "agents", "reviewer", "AGENT.md"), "---\nname: reviewer\ndescription: Reviews changes\nmodel: gpt-5-codex\n---\nReview the change.\n")

	writeCodexTestFile(t, filepath.Join(projectDir, "AGENTS.md"), "Manual project instructions\n")

	provider := &Provider{
		Enabled:   true,
		Name:      "Codex",
		Workspace: "~/.codex",
		Features: map[string]*FeatureConfig{
			"rules":       {Enabled: true, Path: "AGENTS.md"},
			"skills":      {Enabled: true, Path: ".agents/skills"},
			"workflows":   {Enabled: true, Path: ".agents/skills"},
			"permissions": {Enabled: true, Path: ".codex/rules"},
			"agents":      {Enabled: true, Path: ".codex/agents"},
		},
	}
	config := &ProvidersConfig{Providers: map[string]*Provider{"codex": provider}}
	manager := NewProviderManager(config)

	if err := manager.Deploy("codex", cockpitDir, projectDir); err != nil {
		t.Fatalf("first Codex deploy failed: %v", err)
	}
	if err := manager.Deploy("codex", cockpitDir, projectDir); err != nil {
		t.Fatalf("second Codex deploy failed: %v", err)
	}

	assertCodexFileContains(t, filepath.Join(projectDir, "AGENTS.md"), []string{
		"Manual project instructions",
		"<!-- cockpit:global -->",
		"Canonical project context",
		"Keep changes tested.",
		"<!-- /cockpit:global -->",
	})
	assertCodexFileContains(t, filepath.Join(projectDir, ".agents", "skills", "release", "SKILL.md"), []string{
		"name: \"release\"",
		"Run the release checklist.",
	})
	assertCodexFileContains(t, filepath.Join(projectDir, ".agents", "skills", "deploy", "SKILL.md"), []string{
		"# Workflow: deploy",
		"1. test",
		"2. ship",
	})
	assertCodexFileContains(t, filepath.Join(projectDir, ".codex", "rules", "aicockpit.rules"), []string{
		`pattern = ["git", "status"]`,
		`decision = "forbidden"`,
	})
	assertCodexFileContains(t, filepath.Join(projectDir, ".codex", "agents", "reviewer.toml"), []string{
		`name = "reviewer"`,
		`model = "gpt-5-codex"`,
	})

	agents := readCodexTestFile(t, filepath.Join(projectDir, "AGENTS.md"))
	if got := strings.Count(agents, "<!-- cockpit:global -->"); got != 1 {
		t.Errorf("AGENTS.md start marker count = %d, want 1", got)
	}
	if got := strings.Count(agents, "<!-- /cockpit:global -->"); got != 1 {
		t.Errorf("AGENTS.md end marker count = %d, want 1", got)
	}
}

func writeCodexTestFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("create test directory for %s: %v", path, err)
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write test file %s: %v", path, err)
	}
}

func readCodexTestFile(t *testing.T, path string) string {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read test file %s: %v", path, err)
	}
	return string(data)
}

func assertCodexFileContains(t *testing.T, path string, expected []string) {
	t.Helper()
	content := readCodexTestFile(t, path)
	for _, value := range expected {
		if !strings.Contains(content, value) {
			t.Errorf("%s does not contain %q: %s", path, value, content)
		}
	}
}
