package providers

import (
	"fmt"
	"path/filepath"
	"strings"
)

// devinCockpitPermissions lists the minimum Exec permissions that cockpit
// needs to operate inside Devin sessions.
var devinCockpitPermissions = []string{
	"Exec(cockpit)",
	"Exec(make)",
	"Exec(git)",
	"Exec(go)",
	"Exec(gh)",
}

// DevinCompiler compiles assets for the Devin provider.
type DevinCompiler struct{}

// NewDevinCompiler creates a new DevinCompiler.
func NewDevinCompiler() *DevinCompiler {
	return &DevinCompiler{}
}

// Name returns the provider name.
func (d *DevinCompiler) Name() string {
	return "devin"
}

// CompileEntrypoint writes the global memory file and AGENTS.md (rules).
func (d *DevinCompiler) CompileEntrypoint(entrypoint *CanonicalEntrypoint, provider *Provider) (map[string]string, error) {
	files := make(map[string]string)

	grConfig, hasGoldRules := provider.Features["gold_rules"]
	if hasGoldRules && grConfig.Enabled && len(entrypoint.GoldenRules) > 0 {
		var builder strings.Builder
		builder.WriteString("# 🏅 AICockpit Gold Rules\n")
		builder.WriteString("> Auto-generated by `cockpit deploy`. Do not edit directly — edit package manifests and run `cockpit deploy`.\n\n")
		for _, gr := range entrypoint.GoldenRules {
			builder.WriteString(gr)
			builder.WriteString("\n\n")
		}

		files[grConfig.Path] = builder.String()
	}

	rulesConfig, hasRules := provider.Features["rules"]
	if hasRules && rulesConfig.Enabled {
		var builder strings.Builder
		builder.WriteString(AddGeneratedHeader("", "devin"))
		if entrypoint.ProjectContext != "" {
			builder.WriteString(entrypoint.ProjectContext)
			builder.WriteString("\n\n---\n\n")
		}
		files[rulesConfig.Path] = builder.String()
	}

	return files, nil
}

// CompileRules appends standard rules to AGENTS.md.
// Note: In Devin, rules are appended to AGENTS.md
func (d *DevinCompiler) CompileRules(rules []CanonicalRule, provider *Provider) (map[string]string, error) {
	files := make(map[string]string)
	rulesConfig, hasRules := provider.Features["rules"]
	if hasRules && rulesConfig.Enabled && len(rules) > 0 {
		var builder strings.Builder
		for i, r := range rules {
			builder.WriteString(r.Content)
			if i < len(rules)-1 {
				builder.WriteString("\n\n---\n\n")
			}
		}
		files[rulesConfig.Path] = builder.String()
	}
	return files, nil
}

// CompileSkills copies skills to the `.devin/skills` folder.
func (d *DevinCompiler) CompileSkills(skills []CanonicalSkill, provider *Provider) (map[string]string, error) {
	files := make(map[string]string)
	skillsConfig, hasSkills := provider.Features["skills"]
	if hasSkills && skillsConfig.Enabled {
		for _, skill := range skills {
			files[filepath.Join(skillsConfig.Path, skill.Name, "SKILL.md")] = fmt.Sprintf("---\nname: %s\ndescription: %s\n---\n%s", skill.Name, skill.Description, skill.Content)

			for relPath, content := range skill.ScriptFiles {
				files[filepath.Join(skillsConfig.Path, skill.Name, relPath)] = content
			}
		}
	}
	return files, nil
}

// CompileWorkflows translates CanonicalWorkflows into Devin skills and a tools config.
func (d *DevinCompiler) CompileWorkflows(workflows []CanonicalWorkflow, provider *Provider) (map[string]string, error) {
	files := make(map[string]string)
	wfConfig, hasWorkflows := provider.Features["workflows"]
	skillsConfig, hasSkills := provider.Features["skills"]

	if hasWorkflows && wfConfig.Enabled {
		skillsPath := ""
		if hasSkills && skillsConfig.Enabled {
			skillsPath = skillsConfig.Path
		}

		var skillTools strings.Builder

		for _, wf := range workflows {
			safeName := strings.ReplaceAll(wf.Name, "-", "_")

			skillTools.WriteString(fmt.Sprintf(`  - name: %s
    command: "cat %s"
    description: "Follow the %s workflow guide for this task."

`, safeName, filepath.Join(skillsPath, wf.Name, "SKILL.md"), wf.Name))

			if hasSkills && skillsConfig.Enabled {
				var content strings.Builder
				content.WriteString(fmt.Sprintf("# %s\n\n%s\n\n## Steps\n", wf.Name, wf.Description))
				for i, step := range wf.Steps {
					content.WriteString(fmt.Sprintf("%d. %s\n", i+1, step))
				}
				files[filepath.Join(skillsConfig.Path, wf.Name, "SKILL.md")] = fmt.Sprintf("---\nname: %s\ndescription: %s\n---\n%s", wf.Name, wf.Description, content.String())
			}
		}

		content := fmt.Sprintf(`tools:
  - name: run_tests
    command: "make test"
    description: "Run the full test suite and return results."

  - name: lint_check
    command: "make lint"
    description: "Run all linters and check formatting."

%s`, skillTools.String())

		files[wfConfig.Path] = AddGeneratedHeader(content, "config.yaml")
	}
	return files, nil
}

// CompilePermissions reads the config file and merges permissions.
func (d *DevinCompiler) CompilePermissions(perms *CanonicalPermissions, provider *Provider) (map[string]string, error) {
	files := make(map[string]string)
	permConfig, hasPerms := provider.Features["permissions"]

	if hasPerms && permConfig.Enabled {
		expanded, err := expandHome(permConfig.Path)
		if err != nil {
			return nil, err
		}

		m, err := readJSONFile(expanded)
		if err != nil {
			m = make(map[string]interface{})
		}

		permissions := getNestedMap(m, "permissions")
		existingAllow := getStringSliceFromMap(permissions, "allow")
		existingDeny := getStringSliceFromMap(permissions, "deny")
		existingAsk := getStringSliceFromMap(permissions, "ask")

		// Merge allow permissions
		mergedAllow := mergeStringSlice(existingAllow, devinCockpitPermissions)
		if perms != nil {
			mergedAllow = mergeStringSlice(mergedAllow, perms.AllowedCommands)
			mergedAllow = mergeStringSlice(mergedAllow, perms.Allow)
		}

		// Merge deny permissions
		mergedDeny := existingDeny
		if perms != nil {
			mergedDeny = mergeStringSlice(mergedDeny, perms.DeniedCommands)
			mergedDeny = mergeStringSlice(mergedDeny, perms.Deny)
		}

		// Merge ask permissions
		mergedAsk := existingAsk
		if perms != nil {
			mergedAsk = mergeStringSlice(mergedAsk, perms.Ask)
		}

		setStringSliceInMap(permissions, "allow", mergedAllow)
		setStringSliceInMap(permissions, "deny", mergedDeny)
		setStringSliceInMap(permissions, "ask", mergedAsk)
		m["permissions"] = permissions

		err = writeJSONFile(expanded, m)
		if err != nil {
			return nil, err
		}
	}

	return files, nil
}

// CompileAgents copies custom subagent profiles to the agents directory.
func (d *DevinCompiler) CompileAgents(agents []CanonicalAgent, provider *Provider) (map[string]string, error) {
	files := make(map[string]string)
	agentsConfig, hasAgents := provider.Features["agents"]

	if hasAgents && agentsConfig.Enabled {
		for _, agent := range agents {
			// Build frontmatter
			var fm strings.Builder
			fm.WriteString("---\n")
			fm.WriteString(fmt.Sprintf("name: %s\n", agent.Name))
			if agent.Description != "" {
				fm.WriteString(fmt.Sprintf("description: %s\n", agent.Description))
			}
			if agent.Model != "" {
				fm.WriteString(fmt.Sprintf("model: %s\n", agent.Model))
			}
			if len(agent.AllowedTools) > 0 {
				fm.WriteString("allowed-tools:\n")
				for _, tool := range agent.AllowedTools {
					fm.WriteString(fmt.Sprintf("  - %s\n", tool))
				}
			}
			if agent.MaxNesting > 0 {
				fm.WriteString(fmt.Sprintf("max-nesting: %d\n", agent.MaxNesting))
			}
			if agent.Permissions != nil {
				fm.WriteString("permissions:\n")
				if allow, ok := agent.Permissions["allow"].([]string); ok && len(allow) > 0 {
					fm.WriteString("  allow:\n")
					for _, a := range allow {
						fm.WriteString(fmt.Sprintf("    - %s\n", a))
					}
				}
				if deny, ok := agent.Permissions["deny"].([]string); ok && len(deny) > 0 {
					fm.WriteString("  deny:\n")
					for _, d := range deny {
						fm.WriteString(fmt.Sprintf("    - %s\n", d))
					}
				}
				if ask, ok := agent.Permissions["ask"].([]string); ok && len(ask) > 0 {
					fm.WriteString("  ask:\n")
					for _, a := range ask {
						fm.WriteString(fmt.Sprintf("    - %s\n", a))
					}
				}
			}
			fm.WriteString("---\n")

			// Build full AGENT.md content
			var content strings.Builder
			content.WriteString(fm.String())
			content.WriteString("\n")
			content.WriteString(agent.Content)

			files[filepath.Join(agentsConfig.Path, agent.Name, "AGENT.md")] = content.String()
		}
	}
	return files, nil
}
