package providers

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// devinCockpitPermissions lists the minimum Exec permissions that cockpit
// needs to operate inside Devin sessions.
var devinCockpitPermissions = []string{
	"Exec(cockpit)",
	"Exec(make)",
	"Exec(git)",
	"Exec(go)",
	"Exec(gh)",
}

// DevinAdapter compiles assets for the Devin provider.
type DevinAdapter struct{}

// NewDevinAdapter creates a new DevinAdapter.
func NewDevinAdapter() *DevinAdapter {
	return &DevinAdapter{}
}

// Name returns the provider name.
func (d *DevinAdapter) Name() string {
	return "devin"
}

// Compile compiles AGENTS.md, custom skills, config.yaml, and optional permissions.
func (d *DevinAdapter) Compile(cockpitHomeDir string, provider *Provider) (map[string]string, error) {
	files := make(map[string]string)

	// 1. Build AGENTS.md (rules feature)
	rulesConfig, hasRules := provider.Features["rules"]
	if hasRules && rulesConfig.Enabled {
		agentsMd, err := buildAgentsMd(cockpitHomeDir)
		if err != nil {
			return nil, fmt.Errorf("failed to build AGENTS.md: %w", err)
		}
		files[rulesConfig.Path] = agentsMd
	}

	// 2. Build `.agents/skills/` files (skills feature)
	skillsConfig, hasSkills := provider.Features["skills"]
	var skillDirs []string
	if hasSkills && skillsConfig.Enabled {
		skillsSrcDir := filepath.Join(cockpitHomeDir, "skills")
		if _, err := os.Stat(skillsSrcDir); err == nil {
			err = filepath.Walk(skillsSrcDir, func(path string, info os.FileInfo, err error) error {
				if err != nil {
					return err
				}
				if info.IsDir() {
					if path != skillsSrcDir {
						rel, _ := filepath.Rel(skillsSrcDir, path)
						// Keep track of top-level skill directories
						if !strings.Contains(rel, string(filepath.Separator)) {
							skillDirs = append(skillDirs, rel)
						}
					}
					return nil
				}

				relPath, err := filepath.Rel(skillsSrcDir, path)
				if err != nil {
					return err
				}

				content, err := os.ReadFile(path)
				if err != nil {
					return err
				}

				targetPath := filepath.Join(skillsConfig.Path, relPath)
				files[targetPath] = string(content)
				return nil
			})
			if err != nil {
				return nil, fmt.Errorf("failed to walk skills: %w", err)
			}
		}
	}

	// 3. Build `.devin/config.yaml` (workflows feature)
	wfConfig, hasWorkflows := provider.Features["workflows"]
	if hasWorkflows && wfConfig.Enabled {
		skillsPath := ""
		if hasSkills && skillsConfig.Enabled {
			skillsPath = skillsConfig.Path
		}
		configYaml := buildDevinConfigYaml(skillDirs, skillsPath)
		files[wfConfig.Path] = configYaml
	}

	// 4. Apply permissions: merge cockpit Exec grants into ~/.devin/config.local.json
	permConfig, hasPerms := provider.Features["permissions"]
	if hasPerms && permConfig.Enabled {
		if err := d.applyPermissions(permConfig.Path); err != nil {
			return nil, fmt.Errorf("failed to apply devin permissions: %w", err)
		}
	}

	// 5. Write gold_rules to the Devin global memory file (Windsurf global_rules.md)
	// This is what Devin CLI calls "gold rules" — a high-priority always-on rule file.
	grConfig, hasGoldRules := provider.Features["gold_rules"]
	if hasGoldRules && grConfig.Enabled {
		if err := d.writeGoldRules(cockpitHomeDir, grConfig.Path); err != nil {
			return nil, fmt.Errorf("failed to write devin gold rules: %w", err)
		}
	}

	return files, nil
}

// writeGoldRules reads all *-gold-rules.md files from ~/.cockpit/rules/ and
// writes them aggregated to the Devin global memory path (e.g. global_rules.md).
func (d *DevinAdapter) writeGoldRules(cockpitHomeDir, targetPath string) error {
	expanded, err := expandHome(targetPath)
	if err != nil {
		return err
	}

	if err := os.MkdirAll(filepath.Dir(expanded), 0o755); err != nil {
		return fmt.Errorf("failed to create gold rules dir: %w", err)
	}

	rulesDir := filepath.Join(cockpitHomeDir, "rules")
	entries, err := os.ReadDir(rulesDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil // No rules yet, no-op
		}
		return err
	}

	var builder strings.Builder
	builder.WriteString("# 🏅 AICockpit Gold Rules\n")
	builder.WriteString("> Auto-generated by `cockpit deploy`. Do not edit directly — edit package manifests and run `cockpit deploy`.\n\n")

	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), "-gold-rules.md") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(rulesDir, entry.Name()))
		if err != nil {
			return err
		}
		builder.Write(data)
		builder.WriteString("\n")
	}

	return os.WriteFile(expanded, []byte(builder.String()), 0o644)
}

// applyPermissions reads ~/.devin/config.local.json, merges cockpit Exec grants
// (without removing existing ones), and writes it back.
//
// Structure:
//
//	{
//	  "permissions": {
//	    "allow": ["Exec(git)", ...]
//	  }
//	}
func (d *DevinAdapter) applyPermissions(configPath string) error {
	expanded, err := expandHome(configPath)
	if err != nil {
		return err
	}

	m, err := readJSONFile(expanded)
	if err != nil {
		return fmt.Errorf("failed to read %s: %w", expanded, err)
	}

	permissions := getNestedMap(m, "permissions")
	existing := getStringSliceFromMap(permissions, "allow")
	merged := mergeStringSlice(existing, devinCockpitPermissions)
	setStringSliceInMap(permissions, "allow", merged)
	m["permissions"] = permissions

	return writeJSONFile(expanded, m)
}

func buildAgentsMd(cockpitHomeDir string) (string, error) {
	identityPath := filepath.Join(cockpitHomeDir, "identity.md")
	identityContent := ""
	if _, err := os.Stat(identityPath); err == nil {
		data, err := os.ReadFile(identityPath)
		if err != nil {
			return "", err
		}
		identityContent = string(data)
	}

	rulesDir := filepath.Join(cockpitHomeDir, "rules")
	var rules []string
	if _, err := os.Stat(rulesDir); err == nil {
		entries, err := os.ReadDir(rulesDir)
		if err != nil {
			return "", err
		}

		sort.Slice(entries, func(i, j int) bool {
			return entries[i].Name() < entries[j].Name()
		})

		for _, entry := range entries {
			if !entry.IsDir() && filepath.Ext(entry.Name()) == ".md" {
				data, err := os.ReadFile(filepath.Join(rulesDir, entry.Name()))
				if err != nil {
					return "", err
				}
				rules = append(rules, string(data))
			}
		}
	}

	var builder strings.Builder
	builder.WriteString(AddGeneratedHeader("", "devin"))

	if identityContent != "" {
		builder.WriteString(identityContent)
		builder.WriteString("\n\n---\n\n")
	}

	builder.WriteString(strings.Join(rules, "\n\n---\n\n"))
	return builder.String(), nil
}

func buildDevinConfigYaml(skillDirs []string, skillsPath string) string {
	var skillTools strings.Builder
	sort.Strings(skillDirs)
	for _, skillDir := range skillDirs {
		name := strings.ReplaceAll(skillDir, "-", "_")
		readable := toTitleCase(strings.ReplaceAll(skillDir, "-", " "))
		skillTools.WriteString(fmt.Sprintf(`  - name: %s
    command: "cat %s"
    description: "Follow the %s skill guide for this task."

`, name, filepath.Join(skillsPath, skillDir, "SKILL.md"), readable))
	}

	content := fmt.Sprintf(`tools:
  - name: run_tests
    command: "make test"
    description: "Run the full test suite and return results."

  - name: lint_check
    command: "make lint"
    description: "Run all linters and check formatting."

%s`, skillTools.String())

	return AddGeneratedHeader(content, "config.yaml")
}

// toTitleCase converts a space-separated string to Title Case without using
// the deprecated strings.Title function.
func toTitleCase(s string) string {
	words := strings.Fields(s)
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}
